[package]
name = "fm_tree"
version = "0.1.0"
authors = ["Mykola Basov <kolybasov@gmail.com>"]
license = "MIT"

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
clap = "2.31"

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]
